---
- name: Ensure that installation directory exists
  file:
    path: /Applications/Metricbeat
    state: directory

- name: Download metricbeat tarball (workaround)
  shell: "curl https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ elk_version }}-darwin-x86_64.tar.gz -o metricbeat-{{ elk_version }}-darwin-x86_64.tar.gz"

- name: Download and extract
  unarchive:
    src: "~/metricbeat-{{ elk_version }}-darwin-x86_64.tar.gz"
    dest: "{{ mac_install_location }}"
    remote_src: yes

- name: Copy configuration file
  template:
    src: metricbeat.yml.j2
    dest: "{{ mac_install_location }}/metricbeat.yml"
    owner: root
    mode: 0600
  become: yes

- name: Copy service file
  template:
    src: co.elastic.metricbeat.plist
    dest: /Library/LaunchDaemons/co.elastic.metricbeat.plist
  become: yes
  notify: Reload metricbeat mac

- name: Set configuration dir
  set_fact:
    metricbeat_config_dir: "{{ mac_install_location }}"
