---
- name: Install metricbeat from RPM
  yum:
    name: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ elk_version }}-x86_64.rpm"
  become: yes

- name: Copy metricbeat configuration
  template:
    src: metricbeat.yml
    dest: "/etc/metricbeat/metricbeat.yml"
    owner: root
    mode: 0600
  become: yes
  register: metricbeat_service

- name: Restart metricbeat on change
  service:
    name: metricbeat
    state: restarted
  become: yes
  when: metricbeat_service.changed

- name: Enable metricbeat service
  service:
    name: metricbeat
    state: started
    enabled: yes
  become: yes

- name: Set configuration dir
  set_fact:
    metricbeat_config_dir: "/etc/metricbeat"