---
- name: Reload metricbeat mac
  shell: launchctl unload /Library/LaunchDaemons/co.elastic.metricbeat.plist; launchctl load /Library/LaunchDaemons/co.elastic.metricbeat.plist
  become: yes

- name: Reload metricbeat linux
  service:
    name: metricbeat
    state: restarted
  become: yes